version: "3.7"
volumes:
  database:
services:
  db:
    image: mysql:latest
    container_name: trabalhopw2
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=trabalhopw2
      - MYSQL_DATABASE=trabalhopw2
      - MYSQL_USER=trabalhopw2
      - MYSQL_PASSWORD=trabalhopw2