DROP TABLE DESTINATARIO_SEQ;
DROP TABLE Destinatario;
DROP TABLE EMPRESA_SEQ;
DROP TABLE Empresa;
DROP TABLE GRUPO_SEQ;
DROP TABLE Grupo;
DROP TABLE INFORMATIVO_SEQ;
DROP TABLE Informativo;
DROP TABLE USUARIO_SEQ;
DROP TABLE Usuario;

SHOW TABLES;

